blog/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about', views.about, name='about'),
    url(r'^blog', views.blog, name='blog'),
    url(r'^post_list', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^ProductList', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^admin/', views.admin, name='admin'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

cupons/urls.py
from django.conf.urls import url
from cupons.views import CuponApply
from . import views


urlpatterns = [
    url(r'^apply', views.CuponApply, name='apply')
]

magaz/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate')
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from blog.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from blog import *
from cupons.forms import CuponApllyForm


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])

    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })

    cupon_apply_form = CuponApllyForm()

    return render(request, 'cart/detail.html',
                  {'cart': cart, 'cupon_apply_form': cupon_apply_form})

cart/templates/cart/detail.html
{% extends "blog/new-base.html" %}
{% load widget_tweaks %}
{% block title %}
  Ваша корзина товаров
{% endblock %}

{% block content %}
<div class="row">
  <div class="card darken-1 full-width defoult-bg">
    <div class="card-content white-text">
      <span class="card-title center">
        {% if cart.cupon %}
        Price without sale {{ cart.get_total_price }}
        "{{ cart.cupon.code }}" купон на ({{ cart.cupon.discount }} % ниже)
        - {{ cart.get_discount|floatformat:"2" }} BYN
        {% endif %}<br>
        Total price {{ cart.get_total_price_after_discount|floatformat:"2" }} BYN
</span>
<p>Use cupon</p>
<form action="{% url "cupon:apply" %}" method="post" class="add">
  {% csrf_token %}
  {{ cupon_apply_form }}
  <input type="submit" class=""value="Обновить">
</form>
      <table class="bordered">
        <thead>
          <tr class="color-white">
            <th>Name</th>
            <th>Quantity</th>
            <th></th>
            <th>Item Price</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
          {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}" class="tooltipped color-orange" data-position="right" data-delay="50" data-tooltip="{{ product.image.url }}">{{ product.name }}</a>
            </td>
            <td>
              <form id="update" action="{% url "cart:CartAdd" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <input class="noView" type="submit" id="refresh" form="update" value="UPDATE">
                <label class="waves-effect waves-light btn red darken-2" for="refresh">Обновить</label>
              </form>
            </td>
            <td>
              <a href="{% url "cart:CartRemove" product.id %}" class="color-orange">
                Remove
              </a>
            </td>
            <td class="color-orange">{{ item.total_price }} BYN</td>
          </tr>
          {% endwith %}
          {% endfor %}
        </tbody>
      </table>

    </div>
    <div class="card-action center">
      <a href="{% url "blog:ProductList"%}" class="buttonA">Catalog</a>
      <a href="{% url "orders:OrderCreate" %}" class="buttonA">Order</a>
    </div>
  </div>
</div>
{% endblock %}