blog/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about', views.about, name='about'),
    url(r'^blog', views.blog, name='blog'),
    url(r'^post_list', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^ProductList', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^admin/', views.admin, name='admin'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

magaz/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^cupons/', include('cupons.urls', namespace='cupon')),
    url(r'^', include('blog.urls', namespace='blog')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from ckeditor_uploader.fields import RichTextUploadingField


# Модель новостей
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200, verbose_name="Название")
    # text = models.TextField()
    text = RichTextUploadingField(config_name='default')  # текстовый редактор
    full_text = RichTextUploadingField(config_name='default')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ['title']
        verbose_name = 'Пост'
        verbose_name_plural = 'Новости'

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


# Модель автора
class Author(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:ProductListByAuthor', args=[self.slug])


# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:ProductListByCategory', args=[self.slug])


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория", blank=True)
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    # author = models.ForeignKey(Author, related_name='author', verbose_name="Автор")
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name="Изображение товара")
    # description = models.TextField(blank=True, verbose_name="Описание")
    description = RichTextUploadingField(config_name='default', blank=True,
                                         verbose_name="Описание")  # текстовый редактор
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе", blank=True)
    available = models.BooleanField(default=True, verbose_name="Доступен", blank=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)
    updated = models.DateTimeField(auto_now=True, blank=True)
    date = models.PositiveIntegerField(default='2017', verbose_name="Год", blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:ProductDetail', args=[self.id, self.slug])


class Order(models.Model):
    # pic = models.ImageField(blank=True, help_text='150x150px', verbose_name='LOL')
    price = models.CharField(max_length=100, verbose_name='Цена', blank=True, null=True)
    product = models.CharField(max_length=100, verbose_name='Товар', blank=True, null=True)
    name = models.CharField(max_length=20, verbose_name="Имя", blank=True, null=True)
    sername = models.CharField(max_length=20, verbose_name='Фамилия', blank=True, null=True)
    phone = models.PositiveIntegerField(verbose_name='Телефон', blank=True, null=True)
    email = models.EmailField(max_length=30, verbose_name='E-mail', blank=True, null=True)

    # Формат товара
    picture = 'Картина'
    poster = 'Постер'
    FORMAT = (
        (picture, 'Картина'),
        (poster, 'Постер')
    )
    product_format = models.CharField(max_length=50, verbose_name='Формат', choices=FORMAT, default=0)

    # Размер товара
    # A1 = 'A0 (80*120 см)'
    A2 = 'A1 (60*80 см)'
    A3 = 'A2 (40*60 см)'
    A4 = 'A3 (30*40 см)'
    # A5 = 'A4 (20*30 см)''
    SIZE = (
        # (A1, 'A0 (80*120 см)'),
        (A2, 'A1 (60*80 см)'),
        (A3, 'A2 (40*60 см)'),
        (A4, 'A3 (30*40 см)'),
        # (A5, 'A4 (20*30 см)'),
    )
    product_size = models.CharField(max_length=50, verbose_name='Размер', choices=SIZE, default=A4)


    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Заказ: {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

blog/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'sername', 'phone', 'email', 'product_format',
                    'product_size', 'product', 'price']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post
from .models import Category, Product
from cart.forms import CartAddProductForm
from .forms import OrderCreateForm
from django.contrib.auth.models import User


# Страница всех новостей
def about(request): #post_list
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/about.html', {'posts': posts}) #'blog/post_list.html'


# Страница конкретной новости
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


# Начальная страница
def index(request):
    home_page = Post.objects.all().order_by('-pub_date')
    context = {'home_page': home_page}
    return render(request, 'blog/index.html', {'index': index})


# О нас
def post_list(request): #about
    about_page = Post.objects.all().order_by('-pub_date')
    context = {'about_page': about_page}
    return render(request, 'blog/about.html', {'about': about})


# Блог
def blog(request):
    blog_page = Post.objects.all().order_by('-pub_date')
    context = {'blog_page': blog_page}
    return render(request, 'blog/blog_z.html', {'blog': blog})


# Страница с товарами
def ProductList(request, category_slug=None, template='blog/list.html', page_template='blog/list_page.html'):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if request.is_ajax():
        template = page_template
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, template, {
        'category': category,
        'categories': categories,
        'products': products,
        'page_template': page_template
    })


############

# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    form = OrderCreateForm()

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        form.save(commit=True)

    return render(request, 'blog/base_product.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'form': form})


def admin(request):
    if auth.get_user(reuest).is_authenticated:
        return redirect('/admin/')
    else:
        return redirect('/admin/login/?next=/admin/')

blog/templates/blog/about.html
{% extends 'blog/new-base.html' %}


{% block content %}


{% for post in posts %}
  <div class="row">
    <div class="news-conteiner">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <p class="p-news">{{ post.published_date }}</p>
          <span class="card-title">{{ post.title }}</span>
          <p>{{ post.text|safe }}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'blog:post_detail' pk=post.pk %}">More deteil</a>

        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock content %}

blog/templates/blog/base_catalog.html
{% extends 'blog/new-base.html' %}


{% block content %}



		<div id="catalogNav" class="catalogNav-down">
			<div class="catalogNavBlock" {% if not category %} class="selected" {% endif %}>
				<a href="{% url "blog:ProductList" %}" class="catalogNavA">Все</a>
				{% for cat in categories %}
					<a href=""{% if category.slug == cat.slug %} class="selected" {% endif %}></a>
					<a href="{{ cat.get_absolute_url }}" class="catalogNavA">{{ cat.name }}</a>
					<a href="{{ cat.get_absolute_url }}"><img src="{% if cat.image %}{{ cat.image.url }}{% else %}{% endif %}" class="catImage"></img></a>
				{% endfor %}
			</div>
		</div>


		<div class="catalogItems full-width-device">
			{% block product_list %}{% endblock %}
		</div>



{% endblock content %}

blog/templates/blog/base_product.html
{% extends 'blog/new-base.html' %}

{% block content %}
	<div class="col s12 m7 margin-40px">
    <div class="card horizontal card-product">


      <div class="card-image no-img">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% endif %}"  width="" height=""class="no-img">
      </div>


      <div class="card-stacked">
				<h2 class="header text-center">{{ product.name }}</h2>
				<a href="{{ product.category.get_absolute_url }}" class="text-center">{{ product.category }}</a>
        <div class="card-content">
          <p class="text-center">Какое-то описание</p>
					<p class="text-center price-align">Price: {{ product.price}} BYN</p>
        </div>
        <div class="card-action">
					<form action="{% url "cart:CartAdd" product.id %}" method="post">
						<div id="submitButtons">
							<p class="noView">{{ cart_product_form }}</p>
					    {% csrf_token %}
							<input type="submit"  id="addToCart" value="Добавить в корзину">
					    <label class="waves-effect waves-light btn red darken-2" for="addToCart" onclick="Materialize.toast('{{ product.name }} добавлен(а) в карзину', 4000)">
					      Add to cart
					    </label>
							<a href="{% url 'blog:ProductList' %}" class="waves-effect waves-light btn red darken-2 float-right">Catalog</a>
						</div>
					</form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

blog/templates/blog/footer.html
<footer class="page_footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="text-color">Belarusian National Technical University</h5>
        <p class="grey-text text-lighten-4">Faculty of Information Technologies and Robotics</p>
        <p class="grey-text text-lighten-4">Information Technologies Software Support</p>
        <p class="grey-text text-lighten-4">Mark Blin</p>
      </div>
      <div class="col l2 offset-l4 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="{% url 'blog:index' %}">Home</a></li>
          <li><a class="grey-text text-lighten-3" href="{% url 'blog:ProductList' %}">Catalog</a></li>
          <li><a class="grey-text text-lighten-3" href="{% url 'blog:about' %}">About</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer_copyright">
    <div class="container">
      © 2017 EL'Market All Rights Reserved
    </div>
  </div>
</footer>

blog/templates/blog/ico.html
{% load staticfiles %}
<link rel="shortcut icon" href="{% static 'images/logo.ico' %}">

blog/templates/blog/index.html
{% extends 'blog/new-base.html' %}
{% load staticfiles%}

{% block content %}

<center>
<div class="card card1">
	<div class="card-image waves-effect waves-block waves-light">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/Zqn41lMIGg8" frameborder="0" allowfullscreen></iframe>
	</div>
	<div class="card-content">
		<span class="card-title activator grey-text text-darken-4">Good breakfast is a good day</span>
	</div>
</div>
</center>


<center><a href="{% url 'blog:ProductList' %}" class="waves-effect waves-light btn red darken-2">Catalog</a></center>



{% endblock content %}

blog/templates/blog/list.html
{% extends 'blog/base_catalog.html' %}

{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Каталог {% endif %}
{% endblock %}

{% block product_list %}
{% include "blog/list_page.html" %}

{% block js %}
    {{ block.super }}
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>
    <script>$.endlessPaginate({
      onClick: function(context){

      }
        });</script>
{% endblock %}

{% endblock %}

blog/templates/blog/list_page.html
{% load el_pagination_tags %}

{% paginate 16 products %}



  <div class="row">
    {% for product in products %}
    <div class="col s6 m3 full-width-device">
      <div class="card">
        <div class="card-image">
          <img src="{% if product.image %}{{ product.image.url }}{% endif %}"  height="300px">
          <a href="{{ product.get_absolute_url }}" class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a>
        </div>
        <div class="card-content">
          <span class="card-title">{{ product.name }}</span>
          <p>{{ product.price}} BYN.</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

<center>{% show_more "More" "Loading..." %}</center>

blog/templates/blog/new-base.html
{% load staticfiles %}
{% load gtm_tags %}
<html>
<head>
	<title>El'Market</title>
 	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no">
	<link rel="stylesheet" href="{% static 'css/about.css' %}">
	<link rel="stylesheet" href="{% static 'css/footer.css' %}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
	{% block logo %}{% include "blog/ico.html" %}{% endblock %}
</head>
<body>
	{% gtm %}
	<div class="navbar-fixed">
		<nav class="nav nav-down">
			<div class="nav-wrapper">
				<a href="{% url 'blog:index' %}" class="brand-logo">El'Market</a>
				<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
				<ul class="right hide-on-med-and-down">
					<li><a href="{% url 'blog:index' %}">Home</a></li>
					<li><a href="{% url 'blog:ProductList' %}">Catalog</a></li>
					<li><a href="{% url 'blog:about' %}">About</a></li>
					<li>
						<div id="cart">
							{% with total_items=cart|length %}
								{% if cart|length > 0 %}
								<a href="{% url "cart:CartDetail" %}"
								class="tooltipped"
								data-position="bottom" data-delay="50"
								data-tooltip="More deteil">
								Your cart: {{ total_items }} items [{{ cart.get_total_price }} BYN]
								</a>
								{% else %}
									<a href="#" onclick="Materialize.toast('Cart is empty', 4000)">Cart</a>
								{% endif %}
					    {% endwith %}
						</div>
					</li>
					{% if user.is_authenticated %}
						<li class="bg-color-red"><a href="{% url 'blog:admin' %}">Admin panel</a></li>
					{% endif %}
				</ul>

				<ul class="side-nav" id="mobile-demo">
					<li><a href="{% url 'blog:index' %}">Home</a></li>
					<li><a href="{% url 'blog:ProductList' %}">Catalog</a></li>
					<li><a href="{% url 'blog:about' %}">About</a></li>
				</ul>
			</div>
		</nav>
	</div>

	<div class="content_section">
		{% block content %}
		{% endblock %}
	</div>

	{% block footer %}{% include "blog/footer.html" %}{% endblock %}
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
	<script type="text/javascript">
		$(".button-collapse").sideNav();
	</script>
	<script>
		$(function(){
			$(window).scroll(function() {
				if($(this).scrollTop() >= 300) {
				$('nav').addClass('nav-up');
				$('nav').removeClass('nav-down');
				$('#catalogNav').addClass('catalogNav-up');
				$('#catalogNav').removeClass('catalogNav-down');

				}

				else{
				$('nav').removeClass('nav-up');
				$('nav').addClass('nav-down');
				$('#catalogNav').removeClass('catalogNav-up');
				$('#catalogNav').addClass('catalogNav-down');
				}
			});
		});
	</script>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/new-base.html' %}


{% block content %}
<br><br><br><br><br><br>
<div class="post">

	{% if post.published_date %}

	<div class="date">

		{{ post.published_date }}

	</div>

	{% endif %}

	<h1>{{ post.title }}</h1>

	<p>{{ post.text|safe }}</p>

</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/new-base.html' %}


{% block content %}

{% for post in posts %}
	{{ post.published_date }}
	<h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
	<p>{{ post.text|safe }}</p>
{% endfor %}

{% endblock content %}